#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import itertools

def compute():
    name="manjushree"
    output=list(itertools.permutations([x for x in name]))
    print(output)



if __name__=="__main__":
    compute()